Ext.define('BugApp.store.InsectInfo', {
	extend: 'Ext.data.Store',
	config:{
		model: 'BugApp.model.Insect',
		data:[
			{
				id:'aphid',
				spriteFile:001,
				spriteRow:0,
				spriteCol:0,
				insectid:'aphid',
				title:'Aphid',
				type:'Pest',
				actualSize:'fourth',
				actualSizeNum: 'up to 1/4"',
				actualPx:45,
				actualRowPx:0,
				actualColPx:0,
				upto: 'up',
				description:'Soft-bodied rounded insects that range from pin to match-head size. May be black, white, pink, or pale green. They cluster on new growth.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Most vegetables &amp; small fruits.',
				damage:'Suck plant juices. Feeding causes leaf, bud, &amp; flower distortions, curl, &amp; discoloration. Can transmit viral diseases.',
				management:'Use floating row covers. Release lacewings &amp; lady beetles. Hose off aphids w/ a strong blast of water. Spray w/ insecticidal soap.',
				photos:[
					{
						src:'IMG/PHOTOS/aphidsPhoto01.jpg',
						name:'Green peach aphid',
						sciName:'Myzus persicae',
						citation:'USDA'
					},
					{
						src:'IMG/PHOTOS/aphidsPhoto03.jpg',
						name:'Cotton aphid illustration with plant damage',
						sciName:'Aphis gossypii',
						citation:'Art Cushman, USDA'
					},
					{
						src:'IMG/PHOTOS/aphidsPhoto02.jpg',
						name:'Lady bug feeding on pea aphid',
						sciName:'',
						citation:'Scott Bauer, USDA'
					}
				]
				
			},
			{
				id:'appleMaggot',
				spriteFile:001,
				spriteRow:1,
				spriteCol:0,
				insectid:'appleMaggot', 
				title:'Apple Maggot',
				type:'Pest',
				actualSize:'fourth',
				actualSizeNum: '1/4"',
				actualPx:45,
				actualRowPx:-45,
				actualColPx:0,
				upto:'',
				description:'Adults are dark flies w/ transparent banded wings, brown heads, &amp; a white spot on back. Larva are small legless maggots that develop inside fruit. Found throughout North America.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Apples',
				damage:'Fruit dimpled where eggs are laid. Brown tunnels inside fruit. Fruit may drop early.',
				management:'Discard dropped fruit daily. Trap females in sticky red spheres (1 per dwarf tree, 6 for full sized). Grow ground cover to promote ground beetles.',
				photos:[
					{
						src:'IMG/PHOTOS/appleMaggotPhoto03.jpg',
						name:'Apple maggot ',
						sciName:'Rhagoletis pomonella',
						citation:'Joseph Berger'
					}
				]

			},
			{
				id:'asparagusBeetle',
				spriteFile:001,
				spriteRow:2,
				spriteCol:0,
				insectid:'asparagusBeetle', 
				title:'Asparagus Beetle',
				type:'Pest',
				actualSize: 'fourth',
				actualSizeNum: '1/4"',
				actualPx:45,
				actualRowPx:-90,
				actualColPx:0,
				larvaSize: 'third',
				larvaSizeNum:'1/3"',
				larvaPx:55,
				larvaRowPx:-110,
				larvaColPx:-55,
				larvaOrientation:'horizontal',
				upto: '',
				alt:true,
				altColPx:-90,
				description:'Adults have long black wing covers w/ white patches bordered in red. Larva are fat gray grubs w/ black heads &amp; legs. Eggs are black &amp; attached to stems &amp; spears. The Spotted Asparagus Beetle is reddish orange w/ 12 dark spots &amp; the larva is orange.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Asparagus',
				damage:'Chew holes in spears creating brown spots. Consumes leaves from fronds leaving empty branches.',
				management:'Handpick beetles daily. Use floating row cover. Harvest spears frequently.',
				photos:
				[
					{src:'IMG/PHOTOS/asparagusBeetlePhoto01.jpg',name:'Asparagus Beetle ',sciName:'Crioceris asparagi',citation:'http://commons.wikimedia.org/wiki/User:Beentree'},
					{src:'IMG/PHOTOS/asparagusBeetlePhoto02.jpg',name:'Asparagus Beetle Larva',sciName:'Crioceris asparagi',citation:'http://commons.wikimedia.org/wiki/User:Beentree'},
					{src:'IMG/PHOTOS/asparagusBeetlePhoto03.jpg',name:'Spotted Asparagus Beetle',sciName:'Crioceris duodecimpunctata',citation:'Kim Hansen'}
				
				]
				

			},
			{
				id:'asparagusBeetle02',
				spriteFile:001,
				spriteRow:2,
				spriteCol:2,
				insectid:'asparagusBeetle',
				title:'Spotted Asparagus Beetle',
				type:'Pest',
				description:'Spotted Asparagus Beetle\'s have long black wing covers w/ white patches bordered in red. Larva are fat gray grubs w/ black heads &amp; legs. Eggs are black &amp; attached to stems &amp; spears. The Spotted Asparagus Beetle is reddish orange w/ 12 dark spots &amp; the larva is orange.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Asparagus',
				damage:'Chew holes in spears creating brown spots. Consumes leaves from fronds leaving empty branches.'
			},
			{
				id:'assassinBug',
				spriteFile:001,
				spriteRow:3,
				spriteCol:0, 
				insectid:'assassinBug',
				title:'Assassin Bug',
				type:'Beneficial',
				actualSize: 'threefourth',
				actualSizeNum: 'up to 3/4"',
				actualPx:125,
				actualRowPx:-375,
				actualColPx:0,
				upto: '',
				alt:true,
				altColPx:-250,
				description:'Many different species found throughout North America. Colors range from brown, black, red, or gray w/ some brightly colored. Nymphs smaller &amp; look like wingless adults. Adults are flat with narrow heads, curved beak, &amp; long thin legs. May bite &amp; cause a reaction in some.',
				pestControl:'Aphids, cabbage worms, Colorado potato beetles, cucumber beetles, cutworms, earwigs, lined plant bugs, Japanese beetle, lace beetle, Mexican bean beetle, tobacco budworms, tomato hornworms, &amp; other pests.',
				howToAttract:'Present if they have insects to eat. Avoid using pesticides.',
				plantsAffected:'',
				damage:'',
				photos:
				[
					{src:'IMG/PHOTOS/assassinBugPhoto01.jpg',name:'Assassin bug',sciName:'Zelus exsanguis',citation:'Louis Tedders, USDA'},
					{src:'IMG/PHOTOS/assassinBugPhoto02.jpg',name:'Assassin bug nymph',sciName:'Sinea spinipes',citation:'Louis Tedders, USDA'},
					{src:'IMG/PHOTOS/assassinBugPhoto03.jpg',name:'Assassin bug egg',sciName:'',citation:'Charles Olsen, USDA'}
				]
			},
			{
				id:'assassinBug02',
				spriteFile:001,
				spriteRow:3,
				spriteCol:2, 
				insectid:'assassinBug',
				title:'Assassin Bug',
				type:'Beneficial',
				description:'Many different species found throughout North America. Colors range from brown, black, red, or gray w/ some brightly colored. Nymphs smaller &amp; look like wingless adults. Adults are flat with narrow heads, curved beak, &amp; long thin legs. May bite &amp; cause a reaction in some.',
				pestControl:'Aphids, cabbage worms, Colorado potato beetles, cucumber beetles, cutworms, earwigs, lined plant bugs, Japanese beetle, lace beetle, Mexican bean beetle, tobacco budworms, tomato hornworms, &amp; other pests.',
				howToAttract:'Present if they have insects to eat. Avoid using pesticides.',
				plantsAffected:'',
				damage:''
				
			},
			{
				id:'cabbageLooper',
				spriteFile:001,
				spriteRow:5,
				spriteCol:0, 
				insectid:'cabbageLooper',
				title:'Cabbage Looper',
				type:'Pest',
				actualSize: 'threefourth',
				actualSizeNum: '3/4"',
				actualRowPx:-1650,
				actualColPx:0,
				actualPx:125,
				upto:'',
				larvaSize: 'inchhalf',
				larvaSizeNum:'up to 1 1/2"',
				larvaPx:85,
				larvaRowPx:-425,
				larvaColPx:-85,
				larvaOrientation:'horizontal',
				description:'Adults are gray-brown moths w/ a silver V spot on wings. Larva are green caterpillars that arch back into air w/ light lines down their backs &amp; a line on each side. Eggs are green domes on the underside of leaves.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Beets, cabbage, celery, peas, potatoes, spinach, tomatoes, &amp; lettuce.',
				damage:'Chew large holes in leaves. Will tunnel into cabbage heads.',
				management:'Handpick caterpillars &amp; eggs daily. Attract predatory &amp; parasitic insects w/ pollen &amp; nectar plants. Use floating row covers.',
				photos:[
					{src:'IMG/PHOTOS/cabbageLooperPhoto01.jpg',name:'Cabbage looper larva on potato leaves',sciName:'Trichoplusia ni',citation:'Peggy Greb, USDA'},
					{src:'IMG/PHOTOS/cabbageLooperPhoto02.jpg',name:'Cabbage looper',sciName:'Trichoplusia ni',citation:'http://commons.wikimedia.org/wiki/User:Calibas'}
				]	
			},
			{
				id:'cabbageWhite',
				spriteFile:001, 
				spriteRow:4,
				spriteCol:0,
				insectid:'cabbageWhite',
				title:'Cabbage White Butterfly',
				type:'Pest',
				actualSize: 'twoinch',
				actualSizeNum: 'up to 2"',
				actualPx:330,
				actualRowPx:-1320,
				actualColPx:0,
				upto: 'up',
				larvaSize: 'inch',
				larvaSizeNum:'up to 1"',
				larvaPx:165,
				larvaRowPx:-660,
				larvaColPx:-165,
				larvaOrientation:'horizontal',
				description:'Adults are white butterflies w/ black spots seen in most gardens. Larva are green caterpillars w/ yellow stripes.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Broccoli, cabbage, &amp; cauliflower.',
				damage:'Chew large uneven holes in leaves &amp; florets of cauliflower &amp; broccoli. Distribute green pellets as they feed.',
				management:'Handpick caterpillars daily. Use floating row cover. Attract parasitic wasps. Place yellow sticky traps to catch female butterflies.',
				photos:[{src:'IMG/PHOTOS/cabbageWhitePhoto01.jpg',name:'Cabbage white',sciName:'Pieris rapae',citation:'Jerry A. Payne, USDA'},
						{src:'IMG/PHOTOS/cabbageWhitePhoto02.jpg',name:'Cabbage white larva with plant damage',sciName:'Pieris rapae',citation:'Harald Supfle'},
						{src:'IMG/PHOTOS/cabbageWhitePhoto03.jpg',name:'Cabbage white life cycle with plant damage',sciName:'Pieris rapae',citation:'Mary Foley Benson, USDA'}]
				
			},
			{
				id:'chichBug',
				spriteFile:001, 
				spriteRow:6,
				spriteCol:0,
				insectid:'chichBug',
				title:'Chich Bug',
				type:'Pest',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'codlingMoth',
				spriteFile:001, 
				spriteRow:7,
				spriteCol:0,
				insectid:'codlingMoth',
				title:'Codling Moth',
				type:'Pest',
				actualSize: 'threefourth',
				actualSizeNum: '3/4"',
				actualPx:125,
				actualRowPx:-875,
				actualColPx:0,
				upto:'',
				description:'Brown moths w/ wings that have copper patterns &amp; dark brown tips.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Apples, crabapples, &amp; pears.',
				damage:'Fruit will have a (sometimes unnoticeable) hole near the base w/ dark castings coming out of it. Undamaged flesh is edible.',
				management:'Spray dormant oil. Remove cocoons that are under tree bark. Use tree bands of cardboard to trap caterpillars. Tie paper bags around fruit. Attract ground beetles w/ cover crop or mulch.',
				photos:[{src:'IMG/PHOTOS/codlingMothPhoto01.jpg',name:'Codling moth',sciName:'Cydia pomonella',citation:'Scott Bauer, USDA'},
						{src:'IMG/PHOTOS/codlingMothPhoto02.jpg',name:'Codling moth larva feeds on a Red Delicious apple',sciName:'Cydia pomonella',citation:'Doug Wilson,USDA'}]
				
			},
			{
				id:'coloradoPotatoBeetle',
				spriteFile:001,
				spriteRow:8,
				spriteCol:0, 
				insectid:'coloradoPotatoBeetle',
				title:'Colorado Potato Beetle',
				type:'Pest',
				actualSize: 'third',
				actualSizeNum: '1/3"',
				actualPx:55,
				actualRowPx:-440,
				actualColPx:0,
				upto: 'up',
				larvaSize: 'half',
				larvaSizeNum:'1/2"',
				larvaPx:85,
				larvaRowPx:-680,
				larvaColPx:-85,
				larvaOrientation:'horizontal',
				description:'Orangish yellow beetles w/ ten black stripes on wing covers. Larva are reddish orange grubs w/ a row of black spots on both sides. Eggs are upright &amp; yellow &amp; found on the underside of leaves.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Potatoes, tomatoes, &amp; eggplants.',
				damage:'Chew on leaves &amp; stems. Can kill younger plants &amp; defoliate more established crops. On potatoes some damage will not affect yield.',
				management:'Shake plants early in the morning &amp; kill larva &amp; adults. Plant resistant varieties. Mulch plants deeply. Use floating row cover. Release soldier bugs or parasitic wasps.',
				photos:[{src:'IMG/PHOTOS/coloradoPotatoBeetlePhoto01.jpg',name:'Colorado potato beetle devouring a potato leaf',sciName:'Leptinotarsa decemlineata',citation:'Peggy Greb, USDA'},
						{src:'IMG/PHOTOS/coloradoPotatoBeetlePhoto02.jpg',name:'Colorado potato beetle larva on a potato leaf',sciName:'Leptinotarsa decemlineata',citation:'Peggy Greb,USDA'},
						{src:'IMG/PHOTOS/coloradoPotatoBeetlePhoto03.jpg',name:'Colorado potato beetle life cycle with plant damage',sciName:'Leptinotarsa decemlineata',citation:'Mary Foley Benson, USDA'}]
				
			},
			{
				id:'cucumberBeetle',
				spriteFile:001,
				spriteRow:9,
				spriteCol:0, 
				insectid:'cucumberBeetle',
				title:'Cucumber Beetle',
				type:'Pest',
				actualSize: 'fourth',
				actualSizeNum: '1/4"',
				actualPx:45,
				actualRowPx:-405,
				actualColPx:0,
				upto:'',
				alt:true,
				altColPx:-90,
				description:'Look like greenish yellow lady beetles w/ 12 black spots on wing covers. The Striped Cucumber Beetle is oblong, yellowish green in color &amp; marked by three black stripes',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Corn, cucumbers, peanuts, &amp; potatoes.',
				damage:'Larva feed on roots of young plants. Adults chew holes in leaves &amp; fruit. Feeding on established plants cause mostly cosmetic damage. May transmit cucumber mosaic virus &amp; bacterial wilt disease. ',
				management:'Use floating row cover &amp; hand pollinate. Handpick daily.',
				photos:[{src:'IMG/PHOTOS/cucumberBeetlePhoto01.jpg',name:'Spotted cucumber beetle',sciName:'Diabrotica undecimpunctata',citation:'Chris Willis, http://www.flickr.com/photos/arcticpuppy/'},
						{src:'IMG/PHOTOS/cucumberBeetlePhoto02.jpg',name:'Striped cucumber beetle',sciName:'Acalymma vittatum',citation:'Scott Bauer, USDA'},
						{src:'IMG/PHOTOS/cucumberBeetlePhoto03.jpg',name:'Striped cucumber beetle illustration',sciName:'Acalymma vittatum',citation:'Mary Foley Benson, USDA'}]
				
			},
			{
				id:'cucumberBeetle02',
				spriteFile:001,
				spriteRow:9,
				spriteCol:2, 
				insectid:'cucumberBeetle',
				title:'Cucumber Beetle',
				type:'Pest',
				description:'Look like greenish yellow lady beetles w/ 12 black spots on wing covers. The Striped Cucumber Beetle is oblong, yellowish green in color &amp; marked by three black stripes',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Corn, cucumbers, peanuts, &amp; potatoes.',
				damage:'Larva feed on roots of young plants. Adults chew holes in leaves &amp; fruit. Feeding on established plants cause mostly cosmetic damage. May transmit cucumber mosaic virus &amp; bacterial wilt disease. '
				
			},
			{
				id:'earwig',
				spriteFile:001, 
				spriteRow:11,
				spriteCol:0,
				insectid:'earwig',
				title:'Earwig',
				type:'Pest',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'fiveSpottedHawk',
				spriteFile:001, 
				spriteRow:12,
				spriteCol:0,
				insectid:'fiveSpottedHawk',
				title:'Five Spotted Hawk Moth',
				type:'Pest',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				larvaSize: 'h',
				larvaSizeNum:'',
				larvaPx:0,
				larvaRowPx:0,
				larvaColPx:0,
				larvaOrientation:'',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'fleaBeetle',
				spriteFile:001,
				spriteRow:13,
				spriteCol:0, 
				insectid:'fleaBeetle',
				title:'Flea Beetle',
				type:'Pest',
				actualSize: 'eigth',
				actualSizeNum: 'up to 1/8"',
				actualPx:20,
				actualRowPx:-260,
				actualColPx:0,
				upto: '',
				description:'Small black or brown beetles w/ large hind legs that will jump when disturbed.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Most vegetables.',
				damage:'Feeding causes small holes in leaves &amp; can spread viruses. Vigorous plants can w/stand damage. Larva feed on roots.',
				management:'Use floating row cover. Use parasitic nematodes to control larva. Plant vulnerable crops as late as possible.',
				photos:[{src:'IMG/PHOTOS/fleaBeetlePhoto01.jpg',name:'Flea beetle',sciName:'Trachyaphthona sordida',citation:'Peggy Greb, USDA'},
						{src:'IMG/PHOTOS/fleaBeetlePhoto02.jpg',name:'Tuber flea beetle ',sciName:'Epitrix tuberis',citation:'Art Cushman, USDA'}
						]
			},
			{
				id:'groundBeetle',
				spriteFile:001,
				spriteRow:14,
				spriteCol:0, 
				insectid:'groundBeetle',
				title:'Ground Beetle',
				type:'Beneficial',
				actualSize: 'inch',
				actualSizeNum: 'up to 1"',
				actualPx:165,
				actualRowPx:-2310,
				actualColPx:0,
				upto:'',
				larvaSize: 'inch',
				larvaSizeNum:'up to 1"',
				larvaPx:165,
				larvaRowPx:-2310,
				larvaColPx:-165,
				description:'Adults are usually shiny black, but can be metallic green, blue, gold, or red. Larva are dark colored grubs, with 10 segments. Most have mandibles. Feed at night &amp; hide during the day. Many species common in North America.',
				pestControl:'Asparagus beetle, caterpillars, Colorado potato beetles, cutworms, Slugs, snails, squash vine borer, &amp; other pests.',
				howToAttract:'Permanent beds &amp; perennial plantings help protect populations. Stones, rocks, logs, or mulch provide places for them to hide during daytime.',
				plantsAffected:'',
				damage:'',
				photos:[{src:'IMG/PHOTOS/groundBeetlePhoto01.jpg',name:'Ground beetle(boat-backed beetle)',sciName:'Scaphinotus angusticollis',citation:'Greg Schechter, http://www.flickr.com/photos/gregthebusker/'},
						{src:'IMG/PHOTOS/groundBeetlePhoto02.jpg',name:'Ground beetle(tiger beetle)',sciName:'Cicindela sexguttata',citation:'Bruce Marlin, http://www.cirrusimage.com/beetles_green_tiger.htm'}
						]
			},
			

			{
				id:'harlequin',
				spriteFile:002,
				spriteRow:0, 
				spriteCol:0,
				insectid:'harlequin',
				title:'Harlequin Bug',
				type:'Pest',
				actualSize: 'half',
				actualSizeNum: '1/2"',
				actualPx:85,
				actualRowPx:0,
				actualColPx:0,
				upto:'',
				description:'Adults have black &amp; orangish red shield shaped wing cover. Nymphs are wingless &amp; look similar to adults. Found across North America.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Beans, cabbage, corn, peaches, peas, squash, &amp; tomatoes.',
				damage:'Suck plant juices &amp; cause leaves &amp; shoots to blacken &amp; die. Plants may fail to produce fruit.',
				management:'Handpick daily. Remove or mow weedy areas close to garden. Attract parasitic wasps &amp; flies.',
				photos:[
						{src:'IMG/PHOTOS/harlequinPhoto01.jpg',name:'Harlequin bug adult and nymph',sciName:'Murgantia histrionica ',citation:'Linda Tanner, http://www.flickr.com/photos/goingslo/'}
						]
			},
			{
				id:'japaneseBeetle', 
				spriteFile:002,
				spriteRow:1,
				spriteCol:0,
				insectid:'japaneseBeetle',
				title:'Japanese Beetle',
				type:'Pest',
				actualSize: 'half',
				actualSizeNum: '1/2"',
				actualPx:85,
				actualRowPx:-85,
				actualColPx:0,
				upto:'',
				larvaSize: 'threefourth',
				larvaSizeNum:'3/4"',
				larvaPx:125,
				larvaRowPx:-125,
				larvaColPx:-125,
				description:'Metallic green beetles w/ bronze wing covers. Tufts of white hairs can be found on the sides of abdomen. Long legs &amp; big claws. Larva are found in the soil w/ brown heads &amp; C shaped off-white bodies.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Most vegetables.',
				damage:'Adults feed on plants creating lace damage. Leaves may wilt &amp; drop. Larva feed on roots of lawn causing patches of wilted turf.',
				management:'Hand pick adults every morning. If trapping, should be community wide. Nematodes (Heterorhabditis) to control larva.',
				photos:[
						{src:'IMG/PHOTOS/japaneseBeetlePhoto01.jpg',name:'Japanese beetle damage cluster of geranium',sciName:'Popillia japonica',citation:'Stephen Ausmus, USDA'},
						{src:'IMG/PHOTOS/japaneseBeetlePhoto02.jpg',name:'Japanese beetle damage on wine grape',sciName:'Popillia japonica',citation:'USDA'},
						{src:'IMG/PHOTOS/japaneseBeetlePhoto03.jpg',name:'Japanese beetle larva',sciName:'Popillia japonica',citation:'USDA'}
						]
			},
			{
				id:'lacewing',
				spriteFile:002,
				spriteRow:2,
				spriteCol:0, 
				insectid:'lacewing',
				title:'Lacewing',
				type:'Beneficial',
				actualSize: 'inch',
				actualSizeNum: '1"',
				actualPx:165,
				actualRowPx:-330,
				actualColPx:0,
				upto:'',
				larvaSize: 'half',
				larvaSizeNum:'1/2"',
				larvaPx:85,
				larvaRowPx:-170,
				larvaColPx:-85,
				description:'Adults are thin green insects w/ large net-like transparent wings & large eyes. Larva are fast moving & flat brown &amp; white w/ large mandibles. Found all through North America.',
				pestControl:'Aphids, asparagus beetle larva, caterpillars, Colorado potato beetle larva, mealy bugs, scales, spider mites, whiteflies, &amp; other insects.',
				howToAttract:'Plant pollen &amp; nectar flowers including: Angelica, caraway, cosmos, goldenrod, marguerite daisies, Queen Annes lace, tansy, &amp; yarrow. Let a few weeds go to flower such as dandelions. Larva &amp; eggs can be purchased and released widely into the garden.',
				plantsAffected:'',
				damage:'',
				photos:[{src:'IMG/PHOTOS/lacewingPhoto01.jpg',name:'Goldeneyed lacewing',sciName:'Chrysopa oculata',citation:'Stephen Ausmus, USDA'},
						{src:'IMG/PHOTOS/lacewingPhoto02.jpg',name:'Green lacewing larva attacks a cabbage looper larva',sciName:'',citation:'Jack Dykinga, USDA'}
						]
			},
			{
				id:'ladyBug',
				spriteFile:002,
				spriteRow:3,
				spriteCol:0, 
				insectid:'ladyBug',
				title:'Lady Bug',
				type:'Beneficial',
				actualSize: 'third',
				actualSizeNum: '1/3"',
				actualPx:55,
				actualRowPx:-165,
				actualColPx:0,
				upto:'',
				larvaSize: 'third',
				larvaSizeNum:'1/3"',
				larvaPx:55,
				larvaRowPx:-165,
				larvaColPx:-55,
				description:'Adults have round bodies, short legs, &amp; antennae. Colors range from pale-yellow to orange to red, with or without black spots. Can also be solid black, or black with red spots. Larva are black &amp; look like small alligators. Eggs are white or yellow &amp; found in clusters.',
				pestControl:'Aphids, asparagus beetle, colorado beetle, mexican bean beetle, scale, spider mite, whiteflies &amp; other pests.',
				howToAttract:'Diversity of plants with pollen &amp; nectar flowers sustain them when pest populations are low. Some options include dandelions, thyme, yarrow, bugleweed, fennel, cilantro, &amp; dill. Purchased lady bugs are only good for greenhouses; will fly away when released in gardens.',
				plantsAffected:'',
				damage:'',
				photos:[{src:'IMG/PHOTOS/ladyBugPhoto01.jpg',name:'Lady bug',sciName:'Coccinella septempunctata',citation:'Jerry A. Payne, USDA'},
						{src:'IMG/PHOTOS/ladyBugPhoto02.jpg',name:'Lady bug larva',sciName:'Coccinella septempunctata',citation:'Jerry A. Payne, USDA'},
						{src:'IMG/PHOTOS/ladyBugPhoto03.jpg',name:'Lady bug pupa',sciName:'Coccinella septempunctata',citation:'Jerry A. Payne, USDA'}
						]
			},
			{
				id:'leafHopper',
				spriteFile:002, 
				spriteRow:4,
				spriteCol:0,
				insectid:'leafHopper',
				title:'Leaf Hopper',
				type:'Pest',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'prayingMantis',
				spriteFile:002, 
				spriteRow:5,
				spriteCol:0,
				insectid:'prayingMantis',
				title:'Praying Mantis',
				type:'Beneficial',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'mealyBug',
				spriteFile:002, 
				spriteRow:6,
				spriteCol:0,
				insectid:'mealyBug',
				title:'Mealy Bug',
				type:'Pest',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'mexicanBeanBeetle',
				spriteFile:002,
				spriteRow:7,
				spriteCol:0,
				insectid:'mexicanBeanBeetle',
				title:'Mexican Bean Beetle',
				type:'Pest',
				actualSize: 'fourth',
				actualSizeNum: '1/4"',
				actualPx:45,
				actualRowPx:-315,
				actualColPx:0,
				upto: '',
				larvaSize: 'third',
				larvaSizeNum:'1/3"',
				larvaPx:55,
				larvaRowPx:-385,
				larvaColPx:-55,
				description:'Brownish yellow beetles w/ 16 spots on wing covers. Larva are yellowish orange w/ multiple spines. Found in states east of the Mississippi; also in Texas, Arizona, Utah, Colorado, &amp; Nebraska.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Beans: cowpeas, lima beans, snap beans, &amp; soybeans.',
				damage:'Larva &amp; adults feed on the underside of leaves creating lace damage. Leaves can drop &amp; plant may die.',
				management:'Handpick larva &amp; adults daily. Use floating row cover. Attract predators or parasites. Use a trap crop.',
				photos:[{src:'IMG/PHOTOS/mexicanBeanBeetlePhoto01.jpg',name:'Mexican bean beetle and damage',sciName:'Epilachna varivestis',citation:'Jason Riedy, http://www.flickr.com/photos/jason-riedy/'},
						{src:'IMG/PHOTOS/mexicanBeanBeetlePhoto02.jpg',name:'Mexican bean beetle life cycle and damage',sciName:'Epilachna varivestis',citation:'Art Cushman, USDA'},
						{src:'IMG/PHOTOS/mexicanBeanBeetlePhoto03.jpg',name:'Mexican bean beetle larva',sciName:'Epilachna varivestis',citation:'Jason Riedy, http://www.flickr.com/photos/jason-riedy/'}
						]
			},
			{
				id:'scale',
				spriteFile:002,
				spriteRow:9,
				spriteCol:0, 
				insectid:'scale',
				title:'Scale',
				type:'Pest',
				actualSize: 'fourth',
				actualSizeNum: '1/4"',
				actualPx:45,
				actualRowPx:-405,
				actualColPx:0,
				upto:'',
				description:'Females are oval to round, soft, legless, &amp; wingless bumps. Males are small, yellow, &amp; winged. Larva are mobile &amp; look like mealybugs. Found across North America.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Citrus, palms, &amp; roses.',
				damage:'Suck plant sap weakening plants &amp; turning leaves yellow. Leaves may drop &amp; plant could die. Sooty mold or black fungus can be found growing on honeydew secreted by scales.',
				management:'Hand pick scales or remove infested leaves or branches. Attract predatory beetles, lady beetles, or parasitic wasps.',
				photos:[{src:'IMG/PHOTOS/scalePhoto01.jpg',name:'Calico scale',sciName:'Eulecanium cerasorum',citation:'R. Gill, USDA'},
						{src:'IMG/PHOTOS/scalePhoto02.jpg',name:'San Jose scale ',sciName:'Diaspidiotus perniciosus',citation:'Art Cushman, USDA'}
						
						]
			},
			{
				id:'slug',
				spriteFile:002,
				spriteRow:8,
				spriteCol:0, 
				insectid:'slug',
				title:'Slug',
				type:'Pest',
				actualSize: 'eightinch',
				actualSizeNum: 'up to 8"',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto:'',
				pestControl:'',
				howToAttract:'',
				description:'Soft bodied green, black, yellow, tan, or spotted legless pest found across North America. Create mucus trials. Clear oval or round eggs laid in masses under garden debris.',
				plantsAffected:'Most vegetables.',
				damage:'Eat large holes in leaves, stems &amp; bulbs. Prefer tender plants &amp; can destroy seedlings.',
				management:'Pick off every morning. Use small container of beer as trap w/ container lip slightly above soil surface. Surround plants w/ diatomaceous earth to prevent movement.',
				photos:[{src:'IMG/PHOTOS/slugPhoto01.jpg',name:'European red slug',sciName:'Arion rufus',citation:'Gary Bernon, USDA'},
						{src:'IMG/PHOTOS/slugPhoto02.jpg',name:'Dusky slug',sciName:'Arion subfuscus',citation:'Gary Bernon, USDA'}
						]
			},
			{
				id:'spiderMite',
				spriteFile:002,
				spriteRow:10,
				spriteCol:0,
				insectid:'spiderMite',
				title:'Spider Mite',
				type:'Pest',
				actualSize: 'fiftieth',
				actualSizeNum: '1/50"',
				actualPx:5,
				actualRowPx:-50,
				actualColPx:0,
				upto:'',
				pestControl:'',
				howToAttract:'',
				description:'Very small red, green or yellow 8-legged mite with fine hairs found across North America. Most spin webs on the underside of leaves.',
				plantsAffected:'Beans, cucumbers, eggplants, fruit trees, melons, peppers, squash, &amp; tomatoes.',
				damage:'Suck juices from underside of leaves &amp; weakens plant turning leaves yellow to brown. Leaves can drop &amp; fruit may be stunted.',
				management:'Water down plants to reduce reproduction. For greenhouses release predatory mites. Spray insecticidal soap.',
				photos:[{src:'IMG/PHOTOS/spiderMitePhoto01.jpg',name:'Scanning electron micrograph of a two-spotted spider mite feeding on a rose leaf.',sciName:'Tetranychus urticae',citation:'Eric Erbe, USDA'},
						{src:'IMG/PHOTOS/spiderMitePhoto02.jpg',name:'Two-spotted spider mite',sciName:'Tetranychus urticae',citation:'Art Cushman, USDA'},
						{src:'IMG/PHOTOS/spiderMitePhoto03.jpg',name:'Two-spotted spider mite',sciName:'Tetranychus urticae',citation:'Louis Tedders, USDA'}
						]
			},
			{
				id:'squashBug',
				spriteFile:002,
				spriteRow:11,
				spriteCol:0,
				insectid:'squashBug',
				title:'Squash Bug',
				type:'Pest',
				actualSize: 'half',
				actualSizeNum: '1/2"',
				actualPx:85,
				actualRowPx:-935,
				actualColPx:0,
				upto:'',
				description:'Adults are brownish black in color, flat-backed, &amp; covered w/ fine hairs. Nymphs are whitish green or grey; similar shape as adults. Eggs are shiny yellow to brown; found on underside of leaves. Can give off an unpleasant odor in defense.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Pumpkins, squash, &amp; cucurbits.',
				damage:'Suck plant juices &amp; cause leaves &amp; shoots to blacken &amp; die. Plants may fail to produce fruit.',
				management:'Hand pick all bugs from undersides of leaves. Support vines off ground w/ trellis. Control w/ native parasitic flies; attract w/ pollen &amp; nectar plants. Cover Vines w/ floating row cover.',
				photos:[{src:'IMG/PHOTOS/squashBugPhoto01.jpg',name:'Squash bug life cycle and damage. Parasitic fly egg layed in a squash bug',sciName:'',citation:'Art Cushman, USDA'},
						{src:'IMG/PHOTOS/squashBugPhoto02.jpg',name:'Squash bug nymphs',sciName:'Anasa tristis',citation:'http://en.wikipedia.org/wiki/User:Pollinator'}
						]
			},
			{
				id:'squashVineBorer',
				spriteFile:002,
				spriteRow:12,
				spriteCol:0,
				insectid:'squashVineBorer',
				title:'Squash Vine Borer',
				type:'Pest',
				actualSize: 'inch',
				actualSizeNum: '1"',
				actualPx:165,
				actualRowPx:-1980,
				actualColPx:0,
				upto:'',
				description:'Narrow-winged moths; reddish orange abdomens w/ black rings; fringed hind legs &amp; clear wings. White larva w/ brown heads. Eggs are laid on stems &amp; leaf stalks.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Squash family w/ large stems: gourds, pumpkins, &amp; hubbard squash',
				damage:'Larva bore into vine &amp; cause sudden wilting &amp; death of stems.',
				management:'For infested vines, slit stems &amp; remove insects. Cover vines w/ soil to induce rooting. Kill young larva w/ pyrethrin spray at base of plant before they enter stems. Early in season cover vines w/ floating row cover.',
				photos:[{src:'IMG/PHOTOS/squashVineBorerPhoto01.jpg',name:'Squash vine borer life cycle and damage.',sciName:'',citation:'Mary Foley Benson, USDA'}]
			},
			{
				id:'syriphFly',
				spriteFile:002, 
				spriteRow:13,
				spriteCol:0,
				insectid:'syriphFly',
				title:'Syriph Fly',
				type:'Beneficial',
				actualSize: 'h',
				actualSizeNum: '',
				actualPx:0,
				actualRowPx:0,
				actualColPx:0,
				upto: '',
				larvaSize: 'h',
				larvaSizeNum:'',
				larvaPx:0,
				larvaRowPx:0,
				larvaColPx:0,
				larvaOrientation:'',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:'',
				management:'',
				photos:[]
			},
			{
				id:'thrip',
				spriteFile:002,
				spriteRow:14,
				spriteCol:0, 
				insectid:'thrip',
				title:'Thrips',
				type:'Pest',
				actualSize: 'fiftieth',
				actualSizeNum: '1/50"',
				actualPx:5,
				actualRowPx:-70,
				actualColPx:0,
				upto:'',
				description:'Yellowish to brown or black in color. Fast moving; leap or fly when disturbed. Eggs are laid in plant tissues.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Asparagus, cabbage, fruit trees, lettuce, onions, &amp; peas.',
				damage:'Causes silvery speckling or streaks on leaves. Can damage flowers &amp; developing fruit, &amp; can stunt plants.',
				management:'Control w/ predators: pirate bugs, lacewings, or lady beetles. Spray dormant oil on fruit trees. Catch adults w/ blue or yellow sticky traps. Spray insecticidal soap.',
				photos:[{src:'IMG/PHOTOS/thripsPhoto01.jpg',name:'Onion thrips and damage',sciName:'Thrips tabaci',citation:'Art Cushman, USDA'},
						{src:'IMG/PHOTOS/thripsPhoto02.jpg',name:'Melon thrips',sciName:'Thrips palmi',citation:'J. Marie Metz, USDA'}
						]
			},
			{
				id:'whiteFly',
				spriteFile:002,
				spriteRow:15,
				spriteCol:0,
				insectid:'whiteFly', 
				title:'Whitefly',
				type:'Pest',
				actualSize: 'eigth',
				actualSizeNum: 'up to 1/8"',
				actualPx:20,
				actualRowPx:-300,
				actualColPx:0,
				upto:'',
				description:'White winged insects. Adults, nymphs &amp; eggs found on underside of leaves in large numbers.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Asparagus, cabbage, fruit trees, lettuce, onions, &amp; peas.',
				damage:'Plants weakened by adult &amp; nymph feeding. Mold can grow on honeydew that insects secrete. Feeding can spread viral diseases.',
				management:'Vacuum adults from leaves or catch on sticky traps. Spray w/ insecticidal soap. Control w/ native parasitic wasps or predatory beetles.',
				photos:[{src:'IMG/PHOTOS/whiteflyPhoto03.jpg',name:'Silverleaf whitefly',sciName:'Bemisia tabaci Biotype B',citation:'Scott Bauer, USDA'},
						{src:'IMG/PHOTOS/whiteflyPhoto01.jpg',name:'Silverleaf whitefly',sciName:'Bemisia argentifolii',citation:'Scott Bauer, USDA'},
						{src:'IMG/PHOTOS/whiteflyPhoto02.jpg',name:'A tiny pirate bug feeds on whitefly nymphs',sciName:'',citation:'Jack Dykinga, USDA'}
						]
			},

			{
				id:'asparagusBeetleLarva', 
				insectid:'asparagusBeetle',
				spriteFile:001,
				spriteRow:2,
				spriteCol:1,
				title:'Asparagus Beetle',
				type:'Pest',
				description:'Adults have long black wing covers w/ white patches bordered in red. Larva are fat gray grubs w/ black heads &amp; legs. Eggs are black &amp; attached to stems &amp; spears. The Spotted Asparagus Beetle is reddish orange w/ 12 dark spots &amp; the larva is orange.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Asparagus',
				damage:'Chew holes in spears creating brown spots. Consumes leaves from fronds leaving empty branches.'

			},
			{
				id:'cabbageLooperLarva',
				spriteFile:001, 
				spriteRow:5,
				spriteCol:1,
				insectid:'cabbageLooper',
				title:'Cabbage Looper',
				type:'Pest',
				description:'Adults are gray-brown moths w/ a silver V spot on wings. Larva are green caterpillars that arch back into air w/ light lines down their backs &amp; a line on each side. Eggs are green domes on the underside of leaves.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Beets, cabbage, celery, peas, potatoes, spinach, tomatoes, &amp; lettuce.',
				damage:'Chew large holes in leaves. Will tunnel into cabbage heads.'
				
			},
			{
				id:'cabbageWhiteLarva', 
				spriteFile:001,
				spriteRow:4,
				spriteCol:1,
				insectid:'cabbageWhite',
				title:'Cabbage White Butterfly',
				type:'Pest',
				description:'Adults are white butterflies w/ black spots seen in most gardens. Larva are green caterpillars w/ yellow stripes.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Broccoli, cabbage, &amp; cauliflower.',
				damage:'Chew large uneven holes in leaves &amp; florets of cauliflower &amp; broccoli. Distribute green pellets as they feed.'
			},
			{
				id:'coloradoPotatoBeetleLarva',
				spriteFile:001,
				spriteRow:8,
				spriteCol:1, 
				insectid:'coloradoPotatoBeetle',
				title:'Colorado Potato Beetle',
				type:'Pest',
				description:'Orangish yellow beetles w/ ten black stripes on wing covers. Larva are reddish orange grubs w/ a row of black spots on both sides. Eggs are upright &amp; yellow &amp; found on the underside of leaves.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Potatoes, tomatoes, &amp; eggplants.',
				damage:'Chew on leaves &amp; stems. Can kill younger plants &amp; defoliate more established crops. On potatoes some damage will not affect yield.'

				
			},
			{
				id:'cutworm',
				spriteFile:001,
				spriteRow:10,
				spriteCol:1,
				insectid:'cutworm',
				title:'Cutworm',
				type:'Pest',
				larvaSize: 'inchhalf',
				larvaSizeNum: 'up to 1 1/2"',
				upto:'',
				description:'Larva are mostly found in soil &amp; are plump &amp; brown or shiny gray w/ shiny heads. Are slightly buried during the day, curled next to damaged plants.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Most seedlings &amp; transplants.',
				damage:'Larva feed at night on young plants severing the stem near or below the surface of the soil. Seedlings can disappear during the night.',
				management:'Cutworm collars: cardboard, hard plastic, or tin cans w/ both ends removed surrounding seedlings &amp; pressed an inch into the soil. Use parasitic nematodes. Search for larva in the morning around damaged plants. Cultivate a few inches to expose cutworms before planting.',
				photos:[{src:'IMG/PHOTOS/cutwormPhoto01.jpg',name:'Cutworm',sciName:'',citation:'Art Cushman, USDA'},
						{src:'IMG/PHOTOS/cutwormPhoto02.jpg',name:'Bronzed cutworm',sciName:'Nephelodes minians',citation:'John B., http://www.flickr.com/photos/dendroica/'},
						{src:'IMG/PHOTOS/cutwormPhoto03.jpg',name:'Bronzed cutworm',sciName:'Nephelodes minians',citation:'John B., http://www.flickr.com/photos/dendroica/'}
						]
			},
			
			{
				id:'groundBeetleLarva',
				spriteFile:001, 
				spriteRow:14,
				spriteCol:1,
				insectid:'groundBeetle',
				title:'Ground Beetle',
				type:'Beneficial',
				description:'Adults are usually shiny black, but can be metallic green, blue, gold, or red. Larva are dark colored grubs, with 10 segments. Most have mandibles. Feed at night &amp; hide during the day. Many species common in North America.',
				pestControl:'Asparagus beetle, caterpillars, Colorado potato beetles, cutworms, Slugs, snails, squash vine borer, &amp; other pests.',
				howToAttract:'Permanent beds &amp; perennial plantings help protect populations. Stones, rocks, logs, or mulch provide places for them to hide during daytime.',
				plantsAffected:'',
				damage:''
			},
			{
				id:'hornWorm',
				spriteFile:001, 
				spriteRow:12,
				spriteCol:1,
				insectid:'fiveSpottedHawk',
				title:'Hornworm',
				type:'Pest',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:''
			},
			{
				id:'japaneseBeetleLarva', 
				spriteFile:002,
				spriteRow:1,
				spriteCol:1,
				insectid:'japaneseBeetle',
				title:'Japanese Beetle',
				type:'Pest',
				description:'Metallic green beetles w/ bronze wing covers. Tufts of white hairs can be found on the sides of abdomen. Long legs &amp; big claws. Larva are found in the soil w/ brown heads &amp; C shaped off-white bodies.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Most vegetables.',
				damage:'Adults feed on plants creating lace damage. Leaves may wilt &amp; drop. Larva feed on roots of lawn causing patches of wilted turf.'
			},
			{
				id:'ladyBugLarva',
				spriteFile:002, 
				spriteRow:3,
				spriteCol:1,
				insectid:'ladyBug',
				title:'Lady Bug',
				type:'Beneficial',
				description:'Adults have round bodies, short legs, &amp; antennae. Colors range from pale-yellow to orange to red, with or without black spots. Can also be solid black, or black with red spots. Larva are black &amp; look like small alligators. Eggs are white or yellow &amp; found in clusters.',
				pestControl:'Aphids, asparagus beetle, colorado beetle, mexican bean beetle, scale, spider mite, whiteflies &amp; other pests.',
				howToAttract:'Diversity of plants with pollen &amp; nectar flowers sustain them when pest populations are low. Some options include dandelions, thyme, yarrow, bugleweed, fennel, cilantro, &amp; dill. Purchased lady bugs are only good for greenhouses; will fly away when released in gardens.',
				plantsAffected:'',
				damage:''
				
			},
			{
				id:'lacewingLarva',
				spriteFile:002,
				spriteRow:2,
				spriteCol:1, 
				insectid:'lacewing',
				title:'Lacewing',
				type:'Beneficial',
				description:'Adults are thin green insects w/ large net-like transparent wings & large eyes. Larva are fast moving & flat brown &amp; white w/ large mandibles. Found all through North America.',
				pestControl:'Aphids, asparagus beetle larva, caterpillars, Colorado potato beetle larva, mealy bugs, scales, spider mites, whiteflies, &amp; other insects.',
				howToAttract:'Plant pollen &amp; nectar flowers including: Angelica, caraway, cosmos, goldenrod, marguerite daisies, Queen Annes lace, tansy, &amp; yarrow. Let a few weeds go to flower such as dandelions. Larva &amp; eggs can be purchased and released widely into the garden.',
				plantsAffected:'',
				damage:''
				
			},
			{
				id:'mexicanBeanBeetleLarva',
				spriteFile:002,
				spriteRow:7,
				spriteCol:1,
				insectid:'mexicanBeanBeetle',
				title:'Mexican Bean Beetle',
				type:'Pest',
				description:'Brownish yellow beetles w/ 16 spots on wing covers. Larva are yellowish orange w/ multiple spines. Found in states east of the Mississippi; also in Texas, Arizona, Utah, Colorado, &amp; Nebraska.',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'Beans: cowpeas, lima beans, snap beans, &amp; soybeans.',
				damage:'Larva &amp; adults feed on the underside of leaves creating lace damage. Leaves can drop &amp; plant may die.'
				
			},
			{
				id:'syriphFlyLarva',
				spriteFile:002,
				spriteRow:13,
				spriteCol:1,
				insectid:'syriphFly',
				title:'Syriph Fly',
				type:'Beneficial',
				description:'',
				pestControl:'',
				howToAttract:'',
				plantsAffected:'',
				damage:''
				
			},






		]
	
	}
})